import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)" },
  content: { flex: 1, backgroundColor: "#fff", margin: 20, borderRadius: 10 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 15,
  },
  headerTitle: { fontSize: 18, fontWeight: "bold" },
  scrollView: { flex: 1 },
  section: {
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  sectionTitle: { fontSize: 16, fontWeight: "bold", marginBottom: 10 },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 8,
  },
  label: { fontSize: 14, color: "#666" },
  value: { fontSize: 14, color: "#333" },
  itemRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  itemName: { fontSize: 14, flex: 1 },
  itemPrice: { fontSize: 14, color: "#007AFF" },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 15,
    borderTopWidth: 2,
    borderTopColor: "#eee",
  },
  totalLabel: { fontSize: 16, fontWeight: "bold" },
  totalValue: { fontSize: 16, fontWeight: "bold", color: "#007AFF" },
  statusSection: { padding: 15 },
  updateButton: {
    backgroundColor: "#007AFF",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: "center",
  },
  updateButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  body: { flex: 1, paddingHorizontal: 15 },
  infoCard: { backgroundColor: "#f8f9fa", padding: 10, borderRadius: 8 },
  infoRow: { flexDirection: "row", marginVertical: 5 },
  infoLabel: { fontWeight: "bold", marginRight: 5 },
  infoValue: { flex: 1 },
  statusBadge: { paddingVertical: 2, paddingHorizontal: 8, borderRadius: 12 },
  statusText: { color: "#fff", fontSize: 12 },
  orderItem: { marginVertical: 5 },
  itemRowOrder: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  itemNameOrder: { fontSize: 14, flex: 1 },
  itemPriceOrder: { fontSize: 14, color: "#007AFF" },
  totalRowOrder: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 15,
    borderTopWidth: 2,
    borderTopColor: "#eee",
  },
  totalLabelOrder: { fontSize: 16, fontWeight: "bold" },
  totalValueOrder: { fontSize: 16, fontWeight: "bold", color: "#007AFF" },
  statusSectionOrder: { padding: 15 },
  updateButtonOrder: {
    backgroundColor: "#007AFF",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: "center",
  },
  updateButtonTextOrder: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  noItemsText: { fontSize: 14, color: "#6c757d", textAlign: "center" },
  footer: { padding: 15, alignItems: "center" },
  itemTotal: { marginTop: 5 },
  itemTotalText: { fontSize: 14, fontWeight: "bold" },
  totalContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 15,
  },
  totalAmount: { fontSize: 16, fontWeight: "bold", color: "#007AFF" },
});
